module.exports = {
    VALID_EMAIL_MSG: "Please enter valid email",
    USER_NAME_REQUIRED_MSG: "user_name field is required",
    PASSWORD_REQUIRED_MSG: "password field is required",
    DEVICE_TYPE_REQUIRED_MSG: "device_type field is required",
    DEVICE_ID_REQUIRED_MSG: "device_id field is required",
    FCM_TOKEN_REQUIRED_MSG: "fcm_token field is required",
    MEDIA_TYPE_REQUIRED_MSG: "media_type field is required",
    MEDIA_REQUIRED_MSG: "media field is required",
    CAPTION_REQUIRED_MSG: "caption field is required",
    POST_ID_REQUIRED_MSG: "post_id field is required",
    HAS_LIKE_REQUIRED_MSG: "has_like field is required",
    COMMENT_REQUIRED_MSG: "comment field is required",
    FOLLOWING_USER_ID_REQUIRED_MSG: "following_user_id field is required",
    USER_ID_REQUIRED_MSG: "user_id field is required",
    TAG_X_POSITION_REQUIRED_MSG: "tag_x_position field is required",
    TAG_Y_POSITION_REQUIRED_MSG: "tag_y_position field is required",
    OLD_PASSWORD_REQUIRED_MSG: "old_password field is required",
    NEW_PASSWORD_REQUIRED_MSG: "new_password field is required",
    PRODUCT_TITLE_REQUIRED_MSG: "title field is required",
    PRODUCT_DESCRIPTION_REQUIRED_MSG: "description field is required",
    PRODUCT_PRICE_REQUIRED_MSG: "price field is required and should be number greater than 0",
    PRODUCT_ID_REQUIRED_MSG: "product_id field is required",
    PRODUCT_CATEGORY_ID_REQUIRED_MSG: "product_category_id field is required and should be number greater than 0",
    PRODUCT_IMAGE_REQUIRED_ERROR: "product_images field is required",
    CATEGORY_NAME_REQUIRED_MSG: "Category name field is required",
    PRODUCT_QUANTITY_REQUIRED_MSG: "quantity field is required",
    SUB_TOTAL_REQUIRED_MSG: "sub_total field is required and should be number",
    SHIPPING_CHARGES_REQUIRED_MSG: "shipping_charges field is required and should be number",
    TAX_REQUIRED_MSG: "tex field is required and should be number",
    TOTAL_AMOUNT_REQUIRED_MSG: "total_amount field is required and should be number",
    CART_ID_REQUIRED_MSG: "cart_id field is required and should be number"

}