module.exports = {
    DEFAULT_PAGE_NUMBER: 0,
    DEFAULT_PAGE_SIZE: 20,
    SUCCESS: "Success",
    LOGIN_SUCCESS_MSG: "Login successfully",
    USER_NAME_ALREADY_EXIST_MSG: 'username already exist',
    ACCOUNT_WITH_EMAIL_EXIST: 'Account already exist with this email',
    ACCOUNT_NOT_EXIST: "User does not exist",
    INVALID_CREDENTIAL: 'Invalid credential',
    INCORRECT_PASSWORD: 'Incorrect password',
    ACCOUNT_BLOCKED_MSG: 'Your account has been blocked. Please contact with administrator',
    FORGOT_EMAIL_SUCCESS: "Temporary password has been sent to your email",
    UNFOLLOW_SUCCESS: "Unfollow successfully",
    CAN_NOT_FOLLOW_OWN_MSG: "You can not follow own",
    FOLLOWING_USER_NOT_FOUND_MSG: "User that you trying to follow is not exist",
    FOLLOW_SUCCESS: "Follow successfully",
    UNLIKE_SUCCESS: "Like successfully",
    LIKE_SUCCESS: "Unlike successfully",
    POST_ADD_SUCCESS: "Post added successfully",
    POST_DELETE_SUCCESS: "Post deleted successfully",
    COMMENT_ADD_SUCCESS: "Comment added successfully",
    COMMENT_DELETE_SUCCESS: "Comment deleted successfully",
    CATEGORY_ADDED_SUCCESS: "Category added successfully",
    PROFILE_UPDATED_SUCCESS_MSG: "Profile has been updated successfully",
    USER_DELETE_SUCCESS: "User deleted successfully",
    POST_ADDED_SUCCESS: "Post added successfully",
    PASSWORD_UPDATE_SUCCESS_MSG: "Password has been changed successfully",
    INVALID_USER_ID_MSG: "Invalid user id",
    POST_NOT_FOUND_MSG: "Post not found",
    CATEGORY_NOT_EXIST_ERROR: "Category not found",
    PRODUCT_ADDED_SUCCESS: "Product added successfully",
    QUIZ_ADDED_SUCCESS: "Quiz added successfully",
    QUIZ_UPDATED_SUCCESS: "Quiz updated successfully",
    QUIZ_DELETED_SUCCESS: "Quiz deleted successfully",
    QUIZ_QUESTIONS_ADDED_SUCCESS: "Quiz Questions added successfully",
    QUIZ_GET_SUCCESS: "Success",
    QUIZ_GET_QUESTIONS_SUCCESS: "Quiz questions found",
    QUIZ_QUESTIONS_UPDATE_SUCCESS: "Quiz Questions updated successfully",
    QUIZ_QUESTIONS_DELETE_SUCCESS: " Question Deleted successfully",
    FILE_UPLOAD_SUCCESS: "File uploaded successfully",
    FILE_UPLOAD_ERROR: "File upload failed",
    QUIZ_ID_REQUIRED: "Quiz Id required",
    QUESTION_ID_REQUIRED: "Question Id required",


    POST_ID_REQUIRED: "Post id field is required",
    POST_COMMENT_ID_REQUIRED: "Post comment id field is required",
    INVALID_POST_COMMENT_ID_MSG: "Invalid id found",
    INVALID_POST_ID_MSG: "Invalid post id",
    WRONG_OLD_PASSWORD_MSG: "Wrong old password",
    TOKEN_REQUIRED_MSG: "Token is required",
    PRODUCT_ID_REQUIRED_ERROR: "product_id field is required",
    PRODUCT_CATEGORY_ID_REQUIRED_ERROR: "product_category_id field is required",
    PRODUCT_IMAGE_REQUIRED_ERROR: "product_images field is required",
    CATEGORY_ALREADY_EXIST_MSG: "Category name already exist",
    CATEGORY_DELETED_SUCCESS: "Category deleted successfully",
    PRODUCT_DELETED_SUCCESS: "Product deleted successfully",
    PRODUCT_ADDED_IN_CART_SUCCESS: "Product successfully added into cart",
    PRODUCT_UPDATED_IN_CART_SUCCESS: "Product successfully updated into cart",
    INAVLID_PRODUCT_ID_ERROR: "Invalid product id",
    PRODUCT_DELETED_FROM_CART_SUCCESS: "Product successfully deleted from cart",

    NOTIFICATION_GET_SUCCESSFULLY:"Notification get successfully!",
    NOTIFICATION_GET_TYPE_SUCCESSFULLY:"Notification types loded successfully!",
    NOTIFICATION_ADDED_SUCCESSFULLY:"Notification added successfully!",
    NOTIFICATION_UPDATED_SUCCESSFULLY:"Notification updated successfully!",
    NOTIFICATION_DELETED_SUCCESSFULLY:"Notification deleted successfully!",
}
